### ISSUE TITLE
Enhacement of debuging facility

### ISSUE THREAD

**Issue by zigbeefordomoticz** [sasu-drooz/Domoticz-Zigate#965]
It would be nice to be able to specify the Thread we want to get logs. In such we could check all logs for a particular thread.

**Comment by zigbeefordomoticz** [comment]
@SylvainPer

**Comment by SylvainPer** [comment]
Just one thread or multiple choice?

**Comment by pipiche38** [comment]
I think the idea might be to have 
debugThreadForwarder
debugThreadDomoticz
debugThreadZigpy
debugThreadWriter (native Zigate)
debugThreadSerial (native Zigate)

and in that case, this will overwrite the other debug flags

**Comment by SylvainPer** [comment]
#980

**Comment by Hedda** [comment]
FYI, ZHA also features options to separately specify debug logging for each radio library for zigpy as well as other dependencies:

https://    www.home assistant.io/integrations/zha    #debug-logging

### Debug logging

To enable debug logging for Z H A component and radio libraries, add the following [logger](https://www.home-assistant.io/integrations/logger/) configuration to `configuration.yaml`:

```yaml
logger:
  default: info
  logs:
    homeassistant.core: debug
    homeassistant.components.zha: debug
    bellows.zigbee.application: debug
    bellows.ezsp: debug
    zigpy: debug
    zigpy_deconz.zigbee.application: debug
    zigpy_deconz.api: debug
    zigpy_xbee.zigbee.application: debug
    zigpy_xbee.api: debug
    zigpy_zigate: debug
    zigpy_znp: debug
    zhaquirks: debug
```
